### ISSUE TITLE
Unable to customize service

### ISSUE THREAD

**Issue by yating1022** [chromaticnoob/syncplay-android#15]
The software can only use the official server, but its delay is too high for me. I built the server myself, but I can't input it here

**Comment by Et0h** [comment]
While supporting custom servers is a good idea, this is the first complaint I have heard for a long time of latency being too high to use the Syncplay public servers. If you have tried the servers recently and found them to have high latency the please create an issue at https://github.com/Syncplay/syncplay/issues with information such as your country, when you are trying to watch, and what you get from doing a ping of syncplay.pl.

**Comment by chromaticnoob** [comment]
@yating1022 
Joining custom servers will be available in the next update (sometime this week). Thank you for your feedback.

@Et0h From the looks of it he resides somewhere in East Asia (China, I think?). Since Syncplay's official servers are hosted in France, they are ideal for a lot of people, but the east-er you go in Asia the worse it gets (In Australia it can even get up to 400ms).

**Comment by yating1022** [comment]
@Et0h 
Thank you for accepting my suggestion, which will be more convenient for me

**Comment by chromaticnoob** [comment]
@Et0h It might be an issue with the Java-binding ping calculation which I am using, although I've tested it several times but I am gonna break it down more detailedly to see if there is an issue with it.

@yating1022 Custom server input has been added to the latest [version v0.8.0 - BETA](https://github.com/chromaticnoob/syncplay-android/releases/tag/v0.8.0).
